
create table app_user(
	id				bigint 			generated by default as identity primary key,
	inclusion		timestamp		not null,
	exclusion		timestamp,
	name			varchar(300) 	not null,
	email			varchar(200)	not null,
	username		varchar(100)	not null,
	password		varchar(128)	not null,
	active			boolean,
	last_edit_data	timestamp,
	last_login_data	timestamp,
	role			varchar(2)
);


CREATE TABLE study_group (
    id 				BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    group_id		VARCHAR(8)	NOT NULL unique,
    name 			VARCHAR(150) NOT NULL,
    description 	VARCHAR(500),
    urlPhoto		VARCHAR(255),
    inclusion 		TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    exclusion 		TIMESTAMP NULL
);


CREATE TABLE study_group_user (
    id 				BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_user 		BIGINT NOT NULL,
    id_group 		BIGINT NOT NULL,
    group_admin 	BOOLEAN NOT NULL DEFAULT FALSE,
    score			BIGINT,
    inclusion 		TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    exclusion 		TIMESTAMP NULL,
    
    CONSTRAINT fk_study_group_user_user
        FOREIGN KEY (id_user) REFERENCES app_user(id),
        
    CONSTRAINT fk_study_group_user_group
        FOREIGN KEY (id_group) REFERENCES study_group(id)
);


CREATE TABLE study_group_post (
    id 				BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_group 		BIGINT NOT NULL,
    id_group_user 	BIGINT NOT NULL,
    inclusion 		TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    exclusion 		TIMESTAMP NULL,
    title			VARCHAR(150)	NOT NULL,
    description		VARCHAR(500)	NOT NULL,
    date			TIMESTAMP		NOT NULL,
    activityTimeInSeconds	BIGINT	NOT NULL,
    urlPhoto		VARCHAR(255),
    
    CONSTRAINT fk_post_group
        FOREIGN KEY (id_group) REFERENCES study_group(id),
        
    CONSTRAINT fk_post_user
        FOREIGN KEY (id_group_user) REFERENCES study_group_user(id)
);


CREATE TABLE app_user_profile (
    id BIGINT 			PRIMARY KEY,
    id_app_user 		BIGINT NOT NULL UNIQUE,
    inclusion 			TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    exclusion	 		TIMESTAMP NULL,
    profile_image_url 	VARCHAR(255),
    date_of_birth 		TIMESTAMP,
    about 				VARCHAR(2000),
    interests 			VARCHAR(200),
    
    CONSTRAINT fk_app_user_profile_user FOREIGN KEY (id_app_user)
        REFERENCES app_user (id)
);

